### ISSUE TITLE
[Websocket] Url without port is not supported

### ISSUE THREAD

**Issue by gorshkov-leonid** [quarkusio/quarkus-http#24]
I use OpenShift. URLs in routes do not have ports. They look like `https://domain-a.corp.org`. So in java URL object port is -1. But netty does not support this .
```
Caused by: java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
        at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:254)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:123)
        at io.undertow.websockets.jsr.WebsocketConnectionBuilder.connect(WebsocketConnectionBuilder.java:202)
        at io.undertow.websockets.jsr.ServerWebSocketContainer.connectToServerInternal(ServerWebSocketContainer.java:543)
        at io.undertow.websockets.jsr.ServerWebSocketContainer.connectToServerInternal(ServerWebSocketContainer.java:520)
        at io.undertow.websockets.jsr.ServerWebSocketContainer.connectToServer(ServerWebSocketContainer.java:279)
        at mapackage.TestWebSocketService.connect(TestWebSocketService.java:32)
```

I found some mapping in undertow(original):

https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/websockets/client/WebSocketClient.java#L218

But it seems in quarkus there is no similar code

**Comment by gorshkov-leonid** [comment]
@stuartwdouglas I check fix. It is not full. Problem has appeared  on line 201 where connection is created:
```
 b.connect(uri.getHost(), uri.getPort())....
```

**Comment by stuartwdouglas** [comment]
Fixed, although I can't really write a test for it as you can't really bind port 80 for the test...

**Comment by gorshkov-leonid** [comment]
@stuartwdouglas thank you.  On my PC(windows) it was passed successfully. Maybe it is failed because of some docker container limits...

**Comment by gorshkov-leonid** [comment]
As a last resort default port could have been set via System property. But I it seemes ugly.
